# Generated by Django 2.2.5 on 2021-03-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chicken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be distributed'), ('SOLD', 'Item already distributed'), ('NEEDS RESTOCKING', 'Item needs restocking')], default='SOLD', max_length=10)),
                ('description', models.CharField(default='No Issues', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kitchenware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be distributed'), ('SOLD', 'Item already distributed'), ('NEEDS RESTOCKING', 'Item needs restocking')], default='SOLD', max_length=10)),
                ('description', models.CharField(default='No Issues', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
